# Generated by Django 5.0 on 2023-12-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
